import assert from 'node:assert/strict'
import { fillSource } from './source-test-utils.mjs'
import { mkdir, writeFile } from 'node:fs/promises'
import { chromium } from 'playwright'
import { serveProduction } from './serve-production.mjs'
import { verifySelection } from './verify-selection.mjs'

const server = await serveProduction()
let browser
try {
  browser = await chromium.launch({ channel: process.env.EASYM_TEST_BROWSER || undefined })
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
  const errors = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto(server.url)
  const fileAction = async (name) => {
    await page.getByRole('button', { name: 'EM 菜单', exact: true }).click()
    await page.getByRole('menuitem', { name, exact: true }).click()
  }
  const selectTheme = async (theme) => {
    await page.getByRole('button', { name: 'EM 菜单', exact: true }).click()
    assert.equal(await page.getByRole('menuitemradio').count(), 0)
    await page.getByRole('menuitem', { name: 'Style · 配色主题' }).click()
    const parent = await page.locator('.file-menu').boundingBox(), submenu = await page.getByRole('menu', { name: '配色主题', exact: true }).boundingBox()
    assert.ok(submenu.x >= parent.x + parent.width, 'Style submenu opens to the right')
    await page.getByRole('menuitemradio', { name: { light: '清爽浅色', dark: '午夜深色', paper: '暖纸', forest: '护眼绿' }[theme] }).click()
    assert.equal(await page.locator('.application').getAttribute('data-theme'), theme)
  }
  const editor = page.getByRole('textbox', { name: 'Markdown 源码编辑器' })
  const language = page.getByRole('combobox', { name: '代码块语言' })
  const body = () => editor.evaluate((element) => [...element.querySelectorAll('.cm-line')].map((line) => line.textContent).join('\n'))
  assert.equal(await page.locator('.document-status').count(), 0)
  const beforeHide = (await page.locator('.content-grid').boundingBox()).height
  await page.getByRole('button', { name: '隐藏格式工具栏', exact: true }).click()
  assert.equal(await page.getByRole('toolbar').count(), 0)
  assert.ok((await page.locator('.content-grid').boundingBox()).height > beforeHide + 35)
  await page.reload()
  await page.getByRole('button', { name: '显示格式工具栏', exact: true }).click()
  await page.getByRole('toolbar').waitFor()
  const selectionChecks = await verifySelection(page, selectTheme)
  await page.getByRole('button', { name: '分屏', exact: true }).click()
  await fillSource(page, '```javascript\nconst x = 1;\n```\n\n行内 `code`')
  await page.locator('.preview pre code.language-javascript').waitFor()
  await page.locator('.preview .hljs-keyword').waitFor()
  const javascriptHtml = await page.locator('.preview pre code').innerHTML()
  await page.locator('.cm-content .syntax-keyword').waitFor()
  const styles = await page.locator('.preview pre code').evaluate((element) => ({ color: getComputedStyle(element).color, background: getComputedStyle(element).backgroundColor, parentColor: getComputedStyle(element.parentElement).color }))
  assert.equal(styles.color, styles.parentColor)
  assert.equal(styles.background, 'rgba(0, 0, 0, 0)')
  assert.notEqual(await page.locator('.preview p code').evaluate((element) => getComputedStyle(element).backgroundColor), styles.background)
  await editor.press('Control+Home')
  await editor.press('ArrowDown')
  await language.selectOption('python')
  await page.locator('.preview pre code.language-python').waitFor()
  assert.notEqual(await page.locator('.preview pre code').innerHTML(), javascriptHtml)
  assert.equal(await page.locator('.preview .hljs-keyword').count(), 0)
  assert.equal(await body(), '```python\nconst x = 1;\n```\n\n行内 `code`')
  await page.getByRole('button', { name: '撤销', exact: true }).click()
  await page.locator('.preview pre code.language-javascript').waitFor()
  await page.getByRole('button', { name: '重做', exact: true }).click()
  await page.locator('.preview pre code.language-python').waitFor()
  await language.selectOption('')
  await page.waitForFunction(() => document.querySelector('.preview pre code')?.className === '')
  assert.equal(await body(), '```\nconst x = 1;\n```\n\n行内 `code`')

  await fillSource(page, 'print("hello")')
  await editor.press('Control+a')
  await language.selectOption('python')
  await page.getByRole('button', { name: '代码块', exact: true }).click()
  await page.locator('.preview pre code.language-python').waitFor()
  assert.equal(await body(), '```python\nprint("hello")\n```\n')
  await page.getByRole('button', { name: '撤销', exact: true }).click()
  assert.equal(await body(), 'print("hello")')

  const longText = Array.from({ length: 80 }, (_, i) => `## Section ${i}\n\n${'中文 Markdown 段落 '.repeat(12)}\n\n\`\`\`python\nprint(${i})\n\`\`\``).join('\n\n')
  await fillSource(page, longText)
  await page.getByRole('heading', { name: 'Section 79', exact: true }).waitFor()
  const source = page.locator('.cm-scroller')
  const preview = page.locator('.preview')
  await source.evaluate((element) => { element.scrollTop = 0 })
  await page.waitForFunction(() => document.querySelector('.preview').scrollTop === 0)
  // Scrollbar track drag, rather than wheel input only.
  const box = await source.boundingBox()
  await page.mouse.move(box.x + box.width - 5, box.y + 10)
  await page.mouse.down()
  await page.mouse.move(box.x + box.width - 5, box.y + box.height * .5, { steps: 12 })
  await page.mouse.up()
  // Overlay scrollbars may be hidden in headless mode; also exercise a direct thumb-position change.
  await source.evaluate((element) => { element.scrollTop = (element.scrollHeight - element.clientHeight) * .45 })
  await page.waitForFunction(() => document.querySelector('.preview').scrollTop > 1000)
  await page.waitForFunction(() => {
    const s = document.querySelector('.cm-scroller').getBoundingClientRect()
    const p = document.querySelector('.preview').getBoundingClientRect()
    const sourceHeading = [...document.querySelectorAll('.cm-line')].find((line) => line.getBoundingClientRect().top >= s.top && /^## Section \d+/.test(line.textContent))
    const previewHeading = [...document.querySelectorAll('.preview h2')].find((heading) => heading.getBoundingClientRect().top >= p.top)
    return sourceHeading && previewHeading && Math.abs(Number(sourceHeading.textContent.match(/\d+/)[0]) - Number(previewHeading.textContent.match(/\d+/)[0])) <= 1
  })
  // Reverse direction must change only the viewport, without moving the caret.
  await editor.press('Control+Home')
  const caret = await editor.evaluate((element) => window.getSelection()?.anchorOffset)
  await preview.hover()
  await page.mouse.wheel(0, 1600)
  await page.waitForFunction(() => document.querySelector('.cm-scroller').scrollTop > 300)
  assert.equal(await editor.evaluate(() => window.getSelection()?.anchorOffset), caret)
  await preview.evaluate((element) => { element.scrollTop = (element.scrollHeight - element.clientHeight) * .65 })
  await page.waitForFunction(() => {
    const s = document.querySelector('.cm-scroller').getBoundingClientRect(), p = document.querySelector('.preview').getBoundingClientRect()
    const sh = [...document.querySelectorAll('.cm-line')].find((line) => line.getBoundingClientRect().top >= s.top && /^## Section \d+/.test(line.textContent))
    const ph = [...document.querySelectorAll('.preview h2')].find((heading) => heading.getBoundingClientRect().top >= p.top)
    return sh && ph && Math.abs(Number(sh.textContent.match(/\d+/)[0]) - Number(ph.textContent.match(/\d+/)[0])) <= 1
  })
  const stable = await preview.evaluate((element) => element.scrollTop)
  await page.waitForTimeout(400)
  assert.ok(Math.abs(await preview.evaluate((element) => element.scrollTop) - stable) < 2, 'No scroll feedback oscillation')
  await preview.evaluate((element) => { element.scrollTop = element.scrollHeight })
  await page.waitForFunction(() => { const s = document.querySelector('.cm-scroller'); return s.scrollHeight - s.clientHeight - s.scrollTop < 2 })
  await preview.evaluate((element) => { element.scrollTop = 0 })
  await page.waitForFunction(() => document.querySelector('.cm-scroller').scrollTop === 0)
  await source.hover()
  await page.mouse.wheel(0, 600)
  await page.setViewportSize({ width: 960, height: 900 })
  await source.evaluate((element) => { element.scrollTop = (element.scrollHeight - element.clientHeight) * .5 })
  await page.waitForFunction(() => document.querySelector('.preview').scrollTop > 1000)
  await source.evaluate((element) => { element.scrollTop = element.scrollHeight })
  await page.waitForFunction(() => { const p = document.querySelector('.preview'); return p.scrollHeight - p.clientHeight - p.scrollTop < 2 })
  await source.evaluate((element) => { element.scrollTop = 0 })
  await page.waitForFunction(() => document.querySelector('.preview').scrollTop === 0)
  for (const width of [1440, 960]) {
    await page.setViewportSize({ width, height: 900 })
    const layout = await page.locator('.content-grid').boundingBox()
    assert.ok(layout.width >= width * .96, `Editing width at ${width}: ${layout.width}`)
    assert.ok(layout.height > 650, `Editing height: ${layout.height}`)
    assert.equal(await page.locator('.left-sidebar:visible, .right-sidebar:visible').count(), 0)
    assert.ok(await preview.evaluate((element) => element.clientHeight < element.scrollHeight))
    await mkdir('test-results', { recursive: true })
    await page.screenshot({ path: `test-results/writing-${width}.png` })
  }
  await page.getByRole('button', { name: '展开大纲' }).click()
  assert.equal(await page.locator('.right-sidebar:visible').count(), 1)
  // Explicit outline navigation must work even after the preview owns scrolling,
  // and again when the source heading is already visible.
  for (const section of [40, 40, 12, 70]) {
    await preview.hover(); await page.mouse.wheel(0, 400)
    await page.locator('.outline').getByRole('button', { name: `Section ${section}`, exact: true }).click()
    await page.waitForFunction((title) => {
      const visible = (element, pane) => { if (!element) return false; const r = element.getBoundingClientRect(), p = pane.getBoundingClientRect(); return r.top >= p.top - 2 && r.bottom <= p.bottom }
      return visible([...document.querySelectorAll('.cm-line')].find((line) => line.textContent === `## ${title}`), document.querySelector('.cm-scroller')) && visible([...document.querySelectorAll('.preview h2')].find((h) => h.textContent === title), document.querySelector('.preview'))
    }, `Section ${section}`)
  }
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.getByRole('button', { name: '展开文件栏' }).click()
  for (const [side, label, delta] of [['left', '调整文件栏宽度', 70], ['right', '调整大纲栏宽度', -60]]) {
    const sidebar = page.locator(`.${side}-sidebar`)
    const before = (await sidebar.boundingBox()).width
    const grip = await page.getByRole('separator', { name: label }).boundingBox()
    await page.mouse.move(grip.x + grip.width / 2, grip.y + 120); await page.mouse.down()
    await page.mouse.move(grip.x + grip.width / 2 + delta, grip.y + 120, { steps: 10 }); await page.mouse.up()
    assert.ok((await sidebar.boundingBox()).width >= before + 50)
  }
  await page.screenshot({ path: 'test-results/sidebars-outline.png' })
  await page.locator('.pane-actions').getByRole('button', { name: '收起文件栏' }).click()
  await page.locator('.pane-actions').getByRole('button', { name: '收起大纲' }).click()
  assert.equal(await page.locator('.right-sidebar:visible').count(), 0)
  const beforeReadingBody = await body()
  const beforeReadingCount = await page.locator('.statusbar:visible').textContent()
  await page.getByRole('button', { name: '阅读模式', exact: true }).click()
  await page.waitForFunction(() => !!document.fullscreenElement && document.querySelector('.application').classList.contains('reading-mode'))
  assert.equal(await page.locator('.document-strip:visible, .source-pane:visible, .toolbar:visible').count(), 0)
  assert.deepEqual(await page.locator('.view-switcher:visible button').allTextContents(), ['文件树', '大纲', '退出阅读模式'])
  assert.equal(await page.locator('.statusbar:visible').textContent(), beforeReadingCount)
  await page.getByRole('button', { name: '展开大纲' }).click()
  await page.locator('.outline:visible').getByRole('button', { name: 'Section 60', exact: true }).click()
  await page.waitForFunction(() => {
    const p = document.querySelector('.preview').getBoundingClientRect(), h = [...document.querySelectorAll('.preview h2')].find(h => h.textContent === 'Section 60').getBoundingClientRect()
    return h.top >= p.top - 2 && h.bottom < p.bottom
  })
  await page.getByRole('button', { name: '展开文件栏' }).click()
  await page.screenshot({ path: 'test-results/reading-mode.png' })
  await page.locator('.pane-actions:visible').getByRole('button', { name: '收起文件栏' }).click()
  await page.locator('.pane-actions:visible').getByRole('button', { name: '收起大纲' }).click()
  await page.keyboard.press('Escape')
  await page.waitForFunction(() => !document.querySelector('.application').classList.contains('reading-mode'))
  assert.equal(await body(), beforeReadingBody)
  assert.equal(await page.locator('.content-grid.view-split:visible').count(), 1)
  await page.getByRole('button', { name: '阅读模式', exact: true }).click()
  await page.getByRole('button', { name: '退出阅读模式', exact: true }).click()
  await page.waitForFunction(() => !document.fullscreenElement)
  await source.evaluate((element) => { element.scrollTop = element.scrollHeight })
  await page.waitForFunction(() => document.querySelector('.preview').scrollTop > 1000)
  page.once('dialog', (dialog) => dialog.accept())
  await fileAction('新建文档')
  assert.equal(await body(), '')
  assert.equal(await page.getByRole('tab').count(), 2)
  await fillSource(page, 'second note'); await page.waitForTimeout(600); await editor.press('End'); await editor.press('!')
  await page.getByRole('tab').first().click()
  await preview.waitFor({ state: 'visible' })
  await page.waitForFunction(() => document.querySelector('.document-panel:not([hidden]) .preview').scrollTop > 1000)
  await page.getByRole('tab').nth(1).click()
  assert.equal(await body(), 'second note!')
  await page.getByRole('button', { name: '撤销', exact: true }).click()
  assert.equal(await body(), 'second note')
  // Browser file imports also add tabs while preserving all previous edits.
  await page.getByRole('button', { name: '展开文件栏' }).click()
  await page.getByRole('button', { name: 'EM 菜单', exact: true }).click()
  const [picker] = await Promise.all([page.waitForEvent('filechooser'), page.getByRole('menuitem', { name: '打开文件', exact: true }).click()])
  const tableText = '| 名称 | 数值 |\n| :--- | ---: |\n| EasyM | 42 |\n'
  await picker.setFiles({ name: 'third.md', mimeType: 'text/markdown', buffer: Buffer.from('```rust\nfn main() { let x = 1; }\n```\n\n' + tableText) })
  await page.getByRole('tab', { name: 'third.md', exact: true }).waitFor()
  assert.equal(await page.locator('.document-panel:not([hidden]) .left-sidebar').count(), 1)
  assert.equal(await page.getByRole('tab').count(), 3)
  await page.getByRole('button', { name: '分屏', exact: true }).click()
  const visiblePreview = page.locator('.document-panel:not([hidden]) .preview')
  await visiblePreview.locator('.hljs-keyword').first().waitFor()
  const themeColors = []
  const tableBorders = []
  for (const theme of ['light', 'dark', 'paper', 'forest']) {
    await selectTheme(theme)
    themeColors.push(await visiblePreview.evaluate((element) => getComputedStyle(element).backgroundColor))
    const cells = await visiblePreview.locator('th, td').evaluateAll((elements) => elements.map((element) => {
      const style = getComputedStyle(element)
      return { border: style.borderTopWidth, color: style.borderTopColor, kind: style.borderTopStyle, alignment: style.textAlign, background: getComputedStyle(element.closest('.preview')).backgroundColor }
    }))
    assert.ok(cells.length === 4 && cells.every((cell) => cell.border === '1px' && cell.kind === 'solid' && cell.color !== cell.background))
    assert.ok(['right', '-webkit-right'].includes(cells[3].alignment))
    tableBorders.push({ theme, cells })
    await page.screenshot({ path: `test-results/theme-${theme}.png` })
  }
  assert.equal(new Set(themeColors).size, 4)
  await page.waitForTimeout(900)
  await page.reload()
  assert.equal(await page.locator('.application').getAttribute('data-theme'), 'forest')
  await page.getByRole('button', { name: '恢复草稿', exact: true }).click()
  await page.getByRole('tab').nth(1).click()
  await page.getByRole('button', { name: '恢复草稿', exact: true }).click()
  assert.equal(await body(), 'second note')
  // A long current filename stays within the resized file panel.
  await page.getByRole('button', { name: 'EM 菜单', exact: true }).click()
  const [longPicker] = await Promise.all([page.waitForEvent('filechooser'), page.getByRole('menuitem', { name: '打开文件', exact: true }).click()])
  const longName = '非常长的文件名需要省略显示以保护侧栏布局'.repeat(5) + '.md'
  await longPicker.setFiles({ name: longName, mimeType: 'text/markdown', buffer: Buffer.from('# Long name') })
  await page.getByRole('tab', { name: longName, exact: true }).waitFor()
  await page.getByRole('button', { name: '展开文件栏' }).click()
  assert.equal(Math.round((await page.locator('.document-panel:not([hidden]) .left-sidebar').boundingBox()).width), 290)
  const nameLayout = await page.locator('.document-panel:not([hidden]) .current-file-name').evaluate((element) => ({ width: element.clientWidth, scroll: element.scrollWidth, right: element.getBoundingClientRect().right, parentRight: element.closest('.sidebar').getBoundingClientRect().right, ellipsis: getComputedStyle(element).textOverflow }))
  assert.ok(nameLayout.scroll > nameLayout.width && nameLayout.right < nameLayout.parentRight)
  assert.equal(nameLayout.ellipsis, 'ellipsis')
  for (let i = 0; i < 10; i++) await page.getByRole('button', { name: '新建标签', exact: true }).click()
  const untouchedTabs = await page.getByRole('tab').count()
  assert.equal(await page.locator('.document-tab.active [role=tab]').textContent(), '未命名.md')
  await page.locator('.document-tab.active .tab-close').click()
  await page.waitForFunction((count) => document.querySelectorAll('[role=tab]').length === count, untouchedTabs - 1)
  assert.equal(await page.locator('.close-dialog').count(), 0)
  await page.getByRole('button', { name: '新建标签', exact: true }).click()
  const strip = page.getByRole('tablist')
  await editor.hover()
  const hiddenScroll = await strip.evaluate((element) => ({ color: getComputedStyle(element, '::-webkit-scrollbar-thumb').backgroundColor, height: getComputedStyle(element, '::-webkit-scrollbar').height, width: element.clientWidth }))
  assert.equal(hiddenScroll.color, 'rgba(0, 0, 0, 0)')
  assert.equal(hiddenScroll.height, '3px')
  await strip.evaluate((element) => { element.scrollLeft = 0 })
  await strip.hover(); await page.mouse.wheel(0, 600)
  await page.waitForFunction(() => document.querySelector('.document-tablist').scrollLeft > 100)
  const hoverScroll = await strip.evaluate((element) => ({ color: getComputedStyle(element, '::-webkit-scrollbar-thumb').backgroundColor, width: element.clientWidth }))
  assert.notEqual(hoverScroll.color, hiddenScroll.color)
  assert.equal(hoverScroll.width, hiddenScroll.width)
  await page.getByRole('button', { name: 'EM 菜单', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Style · 配色主题' }).click()
  await page.screenshot({ path: 'test-results/em-menu-tabs.png' })
  await page.keyboard.press('Escape')
  await page.keyboard.press('Escape')
  await fillSource(page, 'discard this browser draft'); await page.waitForTimeout(900)
  const tabsBeforeClose = await page.getByRole('tab').count()
  await page.locator('.document-tab.active .tab-close').click()
  await page.getByRole('button', { name: '不保存关闭', exact: true }).click()
  await page.waitForFunction((count) => document.querySelectorAll('[role=tab]').length === count, tabsBeforeClose - 1)
  assert.deepEqual(errors, [])
  const report = { verifiedAt: new Date().toISOString(), browser: await browser.version(), checks: ['code contrast and language-specific source/preview highlighting', 'language insertion/change/removal and undo/redo', 'bidirectional scrolling at middle/top/bottom without caret movement or feedback', 'resize and tab scroll retention', 'multiple files, independent edits and undo histories, draft restart recovery', 'four themes through EM menu and persistent preference', '1440/960 writing area and optional outline', 'outline jumps both panes after preview scrolling and repeated selection', 'both sidebar pointer resizing and width persistence', 'long filename ellipsis', 'EM file menu and wheel navigation of overflowing tabs', 'discard dirty tab without saving', 'untouched new tab closes without confirmation', '3px tab scrollbar transparent until hover without layout shift', 'Style submenu opens only on click to the right', 'save header removed; hideable formatting toolbar and persistent visibility', 'file panel remains open on import into a new tab', 'visible table cell borders and column alignment in all four themes', 'fullscreen read-only preview, three navigation buttons, outline navigation, Escape/button exit and editor retention'], styles, themeColors, tableBorders }
  report.checks.push(...selectionChecks)
  await writeFile('test-results/writing-verification.json', JSON.stringify(report, null, 2) + '\n')
  console.log(JSON.stringify(report, null, 2))
} finally {
  await browser?.close()
  await server.close()
}
