import assert from 'node:assert/strict'
import { mkdir, writeFile } from 'node:fs/promises'
import { chromium } from 'playwright'
import { serveProduction } from './serve-production.mjs'

const server = await serveProduction()
let browser
let page
try {
  browser = await chromium.launch({ channel: process.env.EASYM_TEST_BROWSER || undefined })
  page = await browser.newPage({ viewport: { width: 1280, height: 860 } })
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('dialog', dialog => { void dialog.dismiss() })
  const editor = page.getByRole('textbox', { name: 'Markdown 源码编辑器' })
  const body = () => editor.evaluate((element) => [...element.querySelectorAll('.cm-line')].map((line) => line.textContent).join('\n'))
  await page.goto(server.url)
  await editor.fill('中文 word\nWORD 中文\nwords')
  await page.getByRole('button', { name: '查找 / 替换', exact: true }).click()
  const search = page.getByRole('search', { name: '文档内查找与替换' })
  await search.getByRole('textbox', { name: '查找文本' }).fill('中文')
  await search.getByText('0 / 2 项', { exact: true }).waitFor()
  await search.getByRole('button', { name: '下一项' }).click()
  await search.getByText('1 / 2 项', { exact: true }).waitFor()
  await search.getByRole('button', { name: '下一项' }).click()
  await search.getByText('2 / 2 项', { exact: true }).waitFor()
  await search.getByRole('textbox', { name: '替换为' }).fill('汉字')
  await search.getByRole('button', { name: '替换当前项' }).click()
  assert.equal(await body(), '中文 word\nWORD 汉字\nwords')
  await page.getByRole('button', { name: '撤销', exact: true }).click()
  assert.equal(await body(), '中文 word\nWORD 中文\nwords')
  await search.getByRole('button', { name: '全部替换' }).click()
  assert.equal(await body(), '汉字 word\nWORD 汉字\nwords')
  await page.getByRole('button', { name: '撤销', exact: true }).click()
  assert.equal(await body(), '中文 word\nWORD 中文\nwords')
  await search.getByRole('textbox', { name: '查找文本' }).fill('word')
  await search.getByRole('checkbox', { name: '区分大小写' }).check()
  await search.getByText('0 / 2 项', { exact: true }).waitFor()
  await search.getByRole('checkbox', { name: '整词匹配' }).check()
  await search.getByText('0 / 1 项', { exact: true }).waitFor()
  await search.getByRole('button', { name: '关闭查找' }).click()
  await page.keyboard.press('Control+f')
  await page.getByRole('search', { name: '文档内查找与替换' }).waitFor()
  await search.getByRole('textbox', { name: '查找文本' }).press('Escape')
  assert.equal(await search.count(), 0)
  assert.equal(await page.locator('.cm-searchMatch').count(), 0)
  await editor.fill('alpha alpha alphabet ALPHA\n中文🙂中文\n\\n $1 .*')
  await editor.press('Control+Home')
  await editor.press('Control+f')
  const query = search.getByRole('textbox', { name: '查找文本' })
  await search.getByRole('checkbox', { name: '区分大小写' }).uncheck()
  await search.getByRole('checkbox', { name: '整词匹配' }).uncheck()
  await query.fill('alpha')
  await search.getByText('0 / 4 项', { exact: true }).waitFor()
  await query.press('Enter')
  await search.getByText('1 / 4 项', { exact: true }).waitFor()
  await query.press('Shift+Enter')
  await search.getByText('4 / 4 项', { exact: true }).waitFor()
  await query.fill('.*')
  await search.getByText('0 / 1 项', { exact: true }).waitFor()
  await search.getByRole('textbox', { name: '替换为' }).fill('$1\\n')
  await search.getByRole('button', { name: '全部替换' }).click()
  assert.equal(await body(), 'alpha alpha alphabet ALPHA\n中文🙂中文\n\\n $1 $1\\n')
  await page.getByRole('button', { name: '撤销', exact: true }).click()
  assert.equal(await body(), 'alpha alpha alphabet ALPHA\n中文🙂中文\n\\n $1 .*')
  // Search input composition must not navigate or replace an intermediate query.
  await query.fill('中文')
  await search.getByText('0 / 2 项', { exact: true }).waitFor()
  await query.dispatchEvent('compositionstart', { data: '中' })
  await query.dispatchEvent('keydown', { key: 'Enter', isComposing: true })
  await search.getByRole('button', { name: '全部替换' }).click()
  assert.equal(await body(), 'alpha alpha alphabet ALPHA\n中文🙂中文\n\\n $1 .*')
  await query.dispatchEvent('compositionend', { data: '中文' })
  // Independent tab query/state and close/reopen use the same editor instance.
  await page.getByRole('button', { name: 'EM 菜单', exact: true }).click()
  await page.getByRole('menuitem', { name: '新建文档', exact: true }).click()
  await editor.fill('second tab needle')
  await page.getByRole('button', { name: '查找 / 替换', exact: true }).click()
  await query.fill('needle')
  await search.getByText('0 / 1 项', { exact: true }).waitFor()
  await page.locator('[role="tab"][aria-selected="false"]').first().click()
  const firstQuery = page.getByRole('search', { name: '文档内查找与替换' }).getByRole('textbox', { name: '查找文本' })
  assert.equal(await firstQuery.inputValue(), '中文')
  assert.equal(await body(), 'alpha alpha alphabet ALPHA\n中文🙂中文\n\\n $1 .*')
  await page.locator('[role="tab"][aria-selected="false"]').first().click()
  const secondQuery = page.getByRole('search', { name: '文档内查找与替换' }).getByRole('textbox', { name: '查找文本' })
  assert.equal(await secondQuery.inputValue(), 'needle')
  await search.getByRole('button', { name: '关闭查找' }).click()
  await editor.fill('a'.repeat(10_001))
  await page.getByRole('button', { name: '查找 / 替换', exact: true }).click()
  await query.fill('a')
  await search.getByText('超过 10,000 项', { exact: true }).waitFor()
  assert.equal(await search.getByRole('button', { name: '全部替换' }).isDisabled(), true)
  // Only the latest text/query may update the worker result count.
  await query.fill('nothing')
  await query.fill('aa')
  await search.getByText('0 / 5000 项', { exact: true }).waitFor()
  await search.getByRole('button', { name: '关闭查找' }).click()
  await editor.fill(Array.from({ length: 90 }, (_, i) => `## Section ${i}\n\n${'段落 '.repeat(20)}`).join('\n\n'))
  await editor.press('Control+Home')
  await page.getByRole('button', { name: '分屏', exact: true }).click()
  await page.locator('.preview h2').last().waitFor()
  await page.getByRole('button', { name: '查找 / 替换', exact: true }).click()
  await query.fill('Section 80')
  await search.getByText('0 / 1 项', { exact: true }).waitFor()
  await query.press('Enter')
  await page.waitForFunction(() => {
    const panel = document.querySelector('.document-panel:not([hidden])')
    return panel.querySelector('.preview').scrollTop > 1000 && panel.querySelector('.cm-scroller').scrollTop > 1000
  })
  await page.waitForFunction(() => {
    const preview = document.querySelector('.preview').getBoundingClientRect()
    const heading = [...document.querySelectorAll('.preview h2')].find(h => h.textContent === 'Section 80').getBoundingClientRect()
    return Math.abs(heading.top - preview.top) < 80
  })
  assert.deepEqual(errors, [])
  await mkdir('test-results', { recursive: true })
  const report = { stage: 'v0.2-step-1', verifiedAt: new Date().toISOString(), browser: await browser.version(), passed: true, checks: ['Chinese and emoji source offsets', 'literal query and replacement', 'case and whole word', 'forward/reverse wraparound', 'single/all replacement undo', 'Ctrl+F/Enter/Shift+Enter/Escape', 'search input composition guard (synthetic events)', 'independent tab queries', 'bounded and superseded worker counts', 'split source and preview navigation'] }
  await writeFile('test-results/search-verification.json', JSON.stringify(report, null, 2) + '\n')
  await page.screenshot({ path: 'test-results/search-verification.png' })
  console.log('Search verification passed: Unicode, replace/undo, keyboard/IME guards, tabs, worker limits and split navigation.')
} catch (error) {
  console.error(await page?.evaluate(() => {
    const panel = document.querySelector('.document-panel:not([hidden])')
    const preview = panel?.querySelector('.preview')
    const heading = [...(preview?.querySelectorAll('h2') ?? [])].find(h => h.textContent === 'Section 80')
    return { count: panel?.querySelector('.search-count')?.textContent, sourceTop: panel?.querySelector('.cm-scroller')?.scrollTop, previewTop: preview?.scrollTop, headingTop: heading?.getBoundingClientRect().top, paneTop: preview?.getBoundingClientRect().top }
  }))
  throw error
} finally {
  await browser?.close()
  await server.close()
}
